import nodemailer from "nodemailer";

export default async function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const { name, email, subject, message } = req.body;

  if (!name || !email || !message) {
    return res.status(400).json({ error: 'Name, email, and message are required.' });
  }

  // Zoho Mail SMTP Configuration
  const transporter = nodemailer.createTransport({
    host:'smtp.zoho.in', // Change to smtp.zoho.com if using global version
    port: 465,
    secure: true, // true for 465, false for other ports
    auth: {
      user: process.env.EMAIL_USER, // Your Zoho email (e.g., info@taplinkindia.in)
      pass: process.env.EMAIL_PASS, // Your Zoho App Password (not your login password)
    },
  });

  const mailOptions = {
    from: process.env.EMAIL_USER, // Zoho requires 'from' to be the authenticated user
    replyTo: email, // This allows you to reply directly to the customer
    to: process.env.EMAIL_USER, // Where you want to receive the lead
    subject: `[Lead from TapLink] ${subject || 'New Inquiry'}`,
    text: `
      Name: ${name}
      Email: ${email}
      Subject: ${subject}
      
      Message:
      ${message}
    `,
    html: `
      <div style="font-family: Arial, sans-serif; padding: 20px; color: #333; background-color: #f9f9f9; border-radius: 10px;">
        <h2 style="color: #2563eb; border-bottom: 2px solid #2563eb; padding-bottom: 10px;">New Inquiry from TapLink</h2>
        <div style="margin-top: 20px;">
          <p><strong>Client Name:</strong> ${name}</p>
          <p><strong>Client Email:</strong> ${email}</p>
          <p><strong>Subject:</strong> ${subject}</p>
        </div>
        <div style="margin-top: 20px; padding: 15px; background-color: #fff; border-radius: 8px; border-left: 4px solid #2563eb;">
          <p><strong>Message:</strong></p>
          <p style="white-space: pre-wrap;">${message}</p>
        </div>
        <p style="margin-top: 20px; font-size: 11px; color: #999;">This email was automatically generated by your website's contact form.</p>
      </div>
    `,
  };

  try {
    await transporter.sendMail(mailOptions);
    return res.status(200).json({ message: 'Email sent successfully!' });
  } catch (error) {
    console.error('Nodemailer / Zoho Error:', error);
    return res.status(500).json({ error: 'Failed to send email. Check Zoho credentials.' });
  }
}
